name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Configure AWS CLI
        run: |
          # Configure AWS CLI
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1  # Replace with your desired region
          aws configure set default.output json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify AWS CLI Version
        run: aws --version

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: |
          REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} REACT_APP_INSTAGRAM_TOKEN=${{ secrets.REACT_APP_INSTAGRAM_TOKEN }} npm run build

      - name: Deploy to AWS S3
        run: |
          if [ $GITHUB_REF = 'refs/heads/main' ]; then
            aws s3 sync ./build s3://saramordev.com
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
